---
title: "groundwater_pollution_dk"
author: "Johan Horsmans"
date: "4/26/2021"
output: github_document
---

```{r}
library(pacman)

p_load(sf, raster, dplyr, tmap, ggplot2, tidyverse)
```

```{r}
nitrate <- as.data.frame(read_csv("nitrate/nitrate.csv")) #Load the .csv-file as a dataframe and save it as "nitrates".

nitrateagg <- as.data.frame(read_csv("nitrate/nitrate aggregated.csv")) #Load the .csv-file as a dataframe and save it as "nitrateagg".
```

Processing the nitrate.csv-file into a compatible format.
```{r}
nitrate <- nitrate
nitrate$WKT <- as.character(nitrate$WKT)
nitrate$WKT <- gsub("POINT \\(", "", nitrate$WKT)
nitrate$WKT <- gsub(")", "", nitrate$WKT)
```

Separate into two columns
```{r}
nitrate <- nitrate %>% 
  separate(col = WKT, into = c("longitude","latitude"), sep = " ")

```

Making it a shapefile
```{r}
nitrate <- st_as_sf(nitrate, coords = c("longitude", "latitude"))
```

Plotting the points
```{r}
plot(st_geometry(nitrate))
```

#Agg

```{r}
#test <- structure(list(Shape = c(1.1, 1.1, 1.1, 1.1), 
                    #   long = c(43L, 43L, 40L, 40L), 
                     #  lat = c(10L, 13L, 13L, 10L)), 
                  #class = "data.frame", 
                  #row.names = c("1", "2", "3", "4"))
##

#test <- as.matrix(rbind(test[,-1], test[1, -1]))

#Coord_Ref <- st_crs(3035)
#plot_locations_test <- st_polygon(x = list(test))
#plot_locations_test <- st_sfc(plot_locations_test, crs = Coord_Ref)
#ggplot(plot_locations_test) + geom_sf(fill = "red", alpha = 0.1)
```


```{r}
marker <- st_read("farm_layers/Markblok.shp") %>% na.omit() #loading raster containing farm polygons
```
```{r}
tm_shape(marker) + tm_polygons() #Plotting farms
```
